#!/usr/bin/env bash

function link_file() {
  source_file=$1
  destination_file=$2

  echo "linking $HOME/$destination_file"
  ln $source_file $HOME/$destination_file
}

function check_and_link_file() {
  source_file=$1
  destination_file=$2

  if [ -f $HOME/$destination_file ]; then
    read -p "~/$destination_file already exists. Do you want to override it? (yes/no)" yn
    case $yn in
      yes )
        rm $HOME/$destination_file
        link_file $source_file $destination_file
        ;;
      * ) echo 'skipping...';;
    esac
  else
    link_file $source_file $destination_file
  fi
}

check_and_link_file git/git_config .gitconfig
check_and_link_file git/git_ignore .gitignore

echo "writing $HOME/.bash_profile"
echo ". `pwd`/bash/bash_config" > $HOME/.bash_profile
. $HOME/.bash_profile

# TODO
# export GOPATH=$HOME/code/go
# export PATH=$PATH:$GOPATH/bin
