#!/usr/bin/env bash

. lib/helpers.sh

if ! [[ -e `which brew` ]]; then
  print_with_color $YELLOW "Installing Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if ! [[ `brew list | grep rbenv` ]]; then
  print_with_color $YELLOW "Installing rbenv"
  brew install rbenv
fi

if ! [[ `brew list | grep z` ]]; then
  print_with_color $YELLOW "Installing z"
  brew install z
fi

if ! [[ `brew list | grep wget` ]]; then
  print_with_color $YELLOW "Installing wget"
  brew install wget
fi

if ! [[ `brew list | grep ag` ]]; then
  print_with_color $YELLOW "Installing ag"
  brew install ag
fi

print_with_color $GREEN 'Updating Homebrew'
brew update

. bash/setup_bash.sh
. git/setup_git.sh
. vim/setup_vim.sh
. sublime/setup_sublime.sh
. atom/setup_atom.sh
. iterm/setup_iterm.sh

download_app 'Google Chrome' 'google-chrome'
download_app 'Alfred' 'alfred'
download_app 'Dropbox' 'dropbox'
download_app '1Password' '1password'
download_app 'Spectacle' 'spectacle'

. $HOME/.bash_profile
