#!/usr/bin/env bash

. lib/helpers.sh

if ! [[ -e `which brew` ]]; then
  print_with_color $YELLOW "Installing Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

print_with_color $GREEN 'Updating Homebrew'
brew update

homebrew_install 'rbenv'
homebrew_install 'wget'
homebrew_install 'ag'
homebrew_install 'pass'
homebrew_install 'gpg-agent'
brew install Caskroom/cask/gpgtools
homebrew_install 'gpgtools'
homebrew_install 'pinentry-mac'

. bash/setup_bash.sh
. git/setup_git.sh
. vim/setup_vim.sh
. sublime/setup_sublime.sh
. atom/setup_atom.sh
. iterm/setup_iterm.sh
. gnupg/setup_gnupg.sh

download_app 'Google Chrome' 'google-chrome'
download_app 'Alfred' 'alfred'
download_app 'Dropbox' 'dropbox'
download_app '1Password' '1password'
download_app 'Spectacle' 'spectacle'

. $HOME/.bash_profile
