#!/usr/bin/env bash

echo 'Are you sure that you want to remove your config files? [ Yy / Nn ]:'
read name

case $name in
  [Yy])
    rm $HOME/.gitconfig
    rm $HOME/.gitignore
    rm $HOME/.bash_profile
    echo 'config files uninstalled'
    ;;
  [Nn]) ;;
  *) echo 'Please enter y or n.';;
esac
