syntax on
set expandtab
set tabstop=2
set shiftwidth=2
set wildmode=list:longest
let g:netrw_liststyle=3
set splitbelow
set splitright
set swapfile
set dir=/tmp
colorscheme darkblue

set runtimepath^=~/.vim/bundle/ctrlp.vim
set runtimepath^=~/.vim/bundle/airline.vim

autocmd BufWritePre * :%s/\s\+$//e

set backspace=indent,eol,start

" copy to the clipboard when using yy
set clipboard=unnamed

