# Path to oh-my-zsh
export ZSH=/Users/mat/.oh-my-zsh

ZSH_THEME="robbyrussell"

# Plugins to load (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(brew aws docker mvn pass)

source $ZSH/oh-my-zsh.sh

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

unsetopt autocd extendedglob nomatch
bindkey -v

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/mat/.zshrc'

autoload -Uz compinit
compinit

bindkey -v '^?' backward-delete-char # backspace behaviour aligned with vim behaviour

# hub (Github git extension)
if [[ `brew list | grep hub` ]]; then
  eval "$(hub alias -s)"
  fpath=(~/.zsh/completions $fpath)
  autoload -U compinit && compinit
fi

alias e='vim'

# tmux
alias ta='tmux -CC attach -t'
alias tad='tmux -CC attach -d -t'
alias ts='tmux -CC new-session -s'
alias tl='tmux list-sessions'
alias tksv='tmux kill-server'
alias tkss='tmux kill-session -t'

# git
alias g='git'
alias gadd='git add -u && git add . && git status --short'
alias gs='git status --short'
alias gap='git add --patch'
alias ga='git add'
alias gd='git diff'
alias gc='git commit -m'
alias gpl='git pull --rebase'
alias gps='git push'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gpr='git pull-request'
alias gb='git brach --all --verbose'

# ruby
alias be='bundle exec'

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

