SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# source bash configs
. $SCRIPT_DIR/prompt_config
. $SCRIPT_DIR/color_config
. $SCRIPT_DIR/aliases
. $SCRIPT_DIR/environment

# load git's autocompletion script
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
  __git_complete 'g co' _git_checkout
fi

# subl command
if [ -d /Applications/Sublime\ Text.app/Contents/SharedSupport/bin ]; then
  PATH=$PATH:/Applications/Sublime\ Text.app/Contents/SharedSupport/bin
elif [ -d /Applications/Sublime\ Text\ 3.app/Contents/SharedSupport/bin ]; then
  PATH=$PATH:/Applications/Sublime\ Text\ 3.app/Contents/SharedSupport/bin
elif [ -d /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin ]; then
  PATH=$PATH:/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin
fi

# rbenv
if [ -d /Users/mat/.rbenv ]; then
  eval "$(rbenv init -)"
fi

# VS Code
function code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; }

# hub (Github git extension)
if [[ `brew list | grep hub` ]]; then
  eval "$(hub alias -s)"
fi

# GnuGPG Agent
if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
    source ~/.gnupg/.gpg-agent-info
    export GPG_AGENT_INFO
else
    eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi

# Marked 2
function mark () {
  if [ $1 ]; then
    open -a "Marked 2" $1
  else
    open -a "Marked 2"
  fi
}

# MySQL 5.6
export PATH="/usr/local/opt/mysql@5.6/bin:$PATH"

# python
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
